"""add rfp module tables

Revision ID: f42be6f8a26b
Revises: 
Create Date: 2026-07-29 21:49:44.140678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42be6f8a26b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfp',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('setup_session_id', sa.String(), nullable=True),
    sa.Column('analysis_session_id', sa.String(), nullable=True),
    sa.Column('format_session_id', sa.String(), nullable=True),
    sa.Column('response_session_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfp_chat_message',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rfp_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rfp_id'], ['rfp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfp_document',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rfp_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('analysis_status', sa.String(length=32), nullable=False),
    sa.Column('analysis_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rfp_id'], ['rfp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfp_format_document',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rfp_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rfp_id'], ['rfp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfp_response_document',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rfp_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rfp_id'], ['rfp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: autogenerate also proposed dropping 'employees' and 'departments' —
    # those are pre-existing tables with no matching SQLAlchemy model (untracked,
    # not unused), intentionally left alone here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rfp_response_document')
    op.drop_table('rfp_format_document')
    op.drop_table('rfp_document')
    op.drop_table('rfp_chat_message')
    op.drop_table('rfp')
    op.drop_table('example_records')
    # ### end Alembic commands ###
